version: '3.8'

services:
  eureka-server:
    image: springcloud/eureka
    container_name: eureka-server
    ports:
      - "8761:8761"

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - eureka-server
    environment:
      - SERVICE_NAME=user-service
      - SERVICE_PORT=3001
    ports:
      - "3001:3001"

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - eureka-server
    environment:
      - SERVICE_NAME=product-service
      - SERVICE_PORT=3002
    ports:
      - "3002:3002"

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      - eureka-server
      - product-service
    environment:
      - SERVICE_NAME=order-service
      - SERVICE_PORT=3003
    ports:
      - "3003:3003"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
      - product-service
      - order-service
    environment:
      - SERVICE_NAME=api-gateway
      - SERVICE_PORT=3000
    ports:
      - "3000:3000"
